%% Pre-Processing
clear; clc; close all;
rng('default')
s = rng;

%% Parameters
Integer_Part = 15;
Fractional_Part = 12;
Data_Width = Integer_Part + Fractional_Part;

%% Coefficients
h = [0.5; -0.25; 0.15625; -0.0625];

%% OFDM Symbol Generation
NFFT = 1024;
NumSCinRB = 12;
NusedFFT = 66 * NumSCinRB;
NGuardSC = NFFT - NusedFFT;
NSymbols = 100; % number of OFDM symbols (can change to whatever you want)
ModOrder = 256; 
ofdmmod = comm.OFDMModulator('FFTLength',NFFT,'NumSymbols',NSymbols,'NumGuardBandCarriers',[NGuardSC/2 ; NGuardSC/2]);
msg = randi([0 ModOrder-1], NusedFFT, NSymbols);
modSig = qammod(msg, ModOrder);
OFDMSymbols = ofdmmod(modSig);
OFDMSymbols = real(OFDMSymbols);

%% Fixed Point Object
F = fimath('SumMode', 'SpecifyPrecision', 'SumWordLength', Data_Width,'SumFractionLength', Fractional_Part, 'ProductMode', 'SpecifyPrecision', 'ProductWordLength', Data_Width, 'ProductFractionLength', Fractional_Part);

%% Fixed Point Conversion
OFDMSymbols_fixed = fi(OFDMSymbols, 1, Integer_Part+Fractional_Part, Fractional_Part, F);
h_fixed = fi(h, 1, Integer_Part+Fractional_Part, Fractional_Part, F);

%% Generate Text Files Containing The Inputs to be Passed to the DUT
OFDMSymbols_fixed_bin = OFDMSymbols_fixed.bin;
h_fixed_bin = h_fixed.bin;
fileID1 = fopen('Input_Samples.txt', 'w');
for i = 1 : size(OFDMSymbols_fixed, 1)
    if i == size(OFDMSymbols_fixed,1)
      fprintf(fileID1, '%s', OFDMSymbols_fixed_bin(i, :));
    else
      fprintf(fileID1, '%s\n', OFDMSymbols_fixed_bin(i, :));
    end
end
fileID3 = fopen('coeffs.txt', 'w');
for i = 1 : size(h_fixed, 1)
    if i == size(h_fixed,1)
        fprintf(fileID3, '%s', h_fixed_bin(i, :));
    else
        fprintf(fileID3, '%s\n', h_fixed_bin(i, :));
    end
end

%% Read the Text Files Generated by the RTL to Check the Output
fileID1 = fopen('../Questa_Project/ffe_outputs.txt','r');
content1 = textscan(fileID1, '%s', 'Delimiter', '\n');
rtlOutBinFile = char(string(content1{1}));
rtlOutDecFile = q2dec(rtlOutBinFile, Integer_Part-1, Fractional_Part, 'bin');